### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by dmolsen** [assemble/assemble-pattern-lab#1]
Sorry, I'm a node noob so maybe I missed something. When I tried to install this using `npm i` and then run it with `grunt` I ran into an error where `fs-utils` and `lodash` libraries were missing. Once I got those installed the patterns compiled just fine.

Curious to see where you take this :)

**Comment by jonschlinkert** [comment]
Thanks! I just pushed this up, I'm glad you created the issue. I'll get this fixed now.

**Comment by jonschlinkert** [comment]
Let me know if this works for you!. Thanks again. Btw, I'm happy to collaborate with you on this or take feedback on how this might benefit your community more. 

fwiw, I created this after seeing an issue on one of the pattern lab projects where a user requested Assemble. I totally understood the response and decision to not use Assemble at the time, so I thought it might help show the value of what Assemble can do by just taking the initiative to create an example project. Next my plan was to ping you guys to get feedback, but you beat me to it!

**Comment by dmolsen** [comment]
@jonschlinkert -

Yup, up and running :)

Keep at it. Like I said, I'm curious to see what you come up with. FWIW, I don't think Brad or I approach this as an either/or kind of thing where PL has only one version. We're happy to see an ecosystem where people push the basic concept. It'd be great if they shared similar assets (_e.g. the stuff under `styleguide/` and Mustache-based patterns_) but the thing we're most interested in seeing is modular systems helping folks. We know that's going to come in many different flavors. 

If you can take it and push it with Assemble more power to you :)

**Comment by jonschlinkert** [comment]
Great. I'd be happy to change stuff around to meet the conventions of PL, admittedly I'm just getting familiarized now so there is a lot I don't know about how PL operates - and what is core to the philosophies of the project vs. not. I'm also happy to except any pr if you want to send one my way.

I have a question though, and I couldn't find any answers to this in the docs. 

For clarification, is the organizational structure used in the PL projects part of the actual concept, e.g. how the folders are numbered for example? Based on what I read in the documentation, it seems that the pertinent part is the patterns themselves, meaning "atoms", "molecules" etc. is that correct?

**Comment by dmolsen** [comment]
@jonschlinkert -

The PHP version of Pattern Lab doesn't hardcode atoms, molecules, etc. into the navigation of the viewer. The nav at the top of the [demo](http://demo.pattern-lab.info/) is entirely driven by the file system. To get "templates" before "pages" obviously we had to use numbers since it'd be broken relying on alpha order alone. The cool thing is that this means people can ditch the atomic metaphor, add other steps in between, or whatever they want. Change the file system, regenerate and you're up and running with your own custom thing. This ordering can also be found in the sub-types and patterns themselves. It's important to note that the numbering isn't required if someone is happy just with alpha order.

Unfortunately there's probably a lot of things that would be considered spec for ports that I haven't documented.

**Comment by jonschlinkert** [comment]
I think that answers my question. I was specifically wondering about how these files/folders are numbered and ordered: https://github.com/pattern-lab/patternlab-php/tree/master/core/source/_patterns (both in the node and php versions of the project). thanks!
