### ISSUE TITLE
Circular reference detected error message on clean install

### ISSUE THREAD

**Issue by RyanParsley** [assemble/assemble-pattern-lab#3]
I'm getting this error after a clean install per the readme:

Warning: Circular reference detected (.root.data.root) Use --force to continue

**Comment by jonschlinkert** [comment]
hey @RyanParsley! how you are?

hmm, that sounds like a handlebars-related issue (that might be caused by something here). I'll look into it, thanks for letting us know!

**Comment by RyanParsley** [comment]
I'm great, super busy (aren't we all). I hope you're well. It seems like this message occurs after about 60 or so templates are made. It does not appear to be related to the content of the pattern or the name of the folder/file.

**Comment by jonschlinkert** [comment]
okay, good to know. thanks for the extra info
